version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: purgecss-webpack-plugin
    versions:
    - 4.0.0
    - 4.0.2
